### ISSUE TITLE
No chart data，Why?

### ISSUE THREAD

**Issue by Python-IBM** [smartbetter/dubbo-monitor-simple#2]
I had config all  file，it can show the services,but still no chart data,why?

**Comment by yuxiao97** [comment]
添加这个配置： <dubbo:monitor protocol="registry"/>，启动后，如果发生服务调用，即可看到数据

**Comment by yuxiao97** [comment]
> I had config all file，it can show the services,but still no chart data,why?

添加这个配置： <dubbo:monitor protocol="registry"/>，启动后，如果发生服务调用，即可看到数据
